const INITIAL_LOCATION = 'INITIAL_LOCATION'
const SHOW_PAST_STEP_COUNT = 'SHOW_PAST_STEP_COUNT'
const SHOW_CURRENT_STEP_COUNT = 'SHOW_CURRENT_STEP_COUNT'
const TRACE_USER_PATH = 'TRACE_USER_PATH'
const DELETE_USER_PATH = 'DELETE_USER_PATH'
const SET_TERRITORY_INFO = 'SET_TERRITORY_INFO'
const SET_STEP_COUNT = 'SET_STEP_COUNT'

export { INITIAL_LOCATION, 
         SHOW_PAST_STEP_COUNT,
         SHOW_CURRENT_STEP_COUNT,
         TRACE_USER_PATH,
         DELETE_USER_PATH,
         SET_TERRITORY_INFO,
         SET_STEP_COUNT };